version: "3.3"
services:
  postgres:
    image: sameersbn/postgresql:latest
    container_name: pgsql_spinnaker
    ports:
      - "5432:5432"
    environment:
      - DB_USER=developer
      - DB_PASS=developer
      - DB_NAME=spinnaker
      - DB_EXTENSION="uuid-ossp"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
